//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorApp1.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SfResources_zh__TW {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SfResources_zh__TW() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorApp1.Resources.SfResources.zh -TW", typeof(SfResources_zh__TW).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 添加新卡 的當地語系化字串。
        /// </summary>
        public static string Kanban_AddTitle {
            get {
                return ResourceManager.GetString("Kanban_AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        public static string Kanban_Cancel {
            get {
                return ResourceManager.GetString("Kanban_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇的卡 的當地語系化字串。
        /// </summary>
        public static string Kanban_CardsSelected {
            get {
                return ResourceManager.GetString("Kanban_CardsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string Kanban_Delete {
            get {
                return ResourceManager.GetString("Kanban_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您確定要刪除此卡嗎？ 的當地語系化字串。
        /// </summary>
        public static string Kanban_DeleteContent {
            get {
                return ResourceManager.GetString("Kanban_DeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除卡 的當地語系化字串。
        /// </summary>
        public static string Kanban_DeleteTitle {
            get {
                return ResourceManager.GetString("Kanban_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯卡的詳細信息 的當地語系化字串。
        /// </summary>
        public static string Kanban_EditTitle {
            get {
                return ResourceManager.GetString("Kanban_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 項目 的當地語系化字串。
        /// </summary>
        public static string Kanban_Items {
            get {
                return ResourceManager.GetString("Kanban_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最大限度 的當地語系化字串。
        /// </summary>
        public static string Kanban_Max {
            get {
                return ResourceManager.GetString("Kanban_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 敏 的當地語系化字串。
        /// </summary>
        public static string Kanban_Min {
            get {
                return ResourceManager.GetString("Kanban_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不 的當地語系化字串。
        /// </summary>
        public static string Kanban_No {
            get {
                return ResourceManager.GetString("Kanban_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 保存 的當地語系化字串。
        /// </summary>
        public static string Kanban_Save {
            get {
                return ResourceManager.GetString("Kanban_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是的 的當地語系化字串。
        /// </summary>
        public static string Kanban_Yes {
            get {
                return ResourceManager.GetString("Kanban_Yes", resourceCulture);
            }
        }
    }
}
